version: '2'
networks:
    app:
        driver: 'bridge'

services:
    web:
        build:
            context: .
            dockerfile: .docker/web/Dockerfile
        volumes:
            - .:/opt/projects
        container_name: web
        ports:
            - "8000:80"
        networks:
            - app
        stdin_open: true
        tty: true
